// lib/domain/models/regional_guide_entry.dart
//
// Data model for the Regional Guide feature (post-MVP).
// See docs/05-features/01-regional-guide.md for full spec.
//
// Not used in MVP — included so the model is ready when
// the feature is built in a future phase.

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:uuid/uuid.dart';

part 'regional_guide_entry.freezed.dart';
part 'regional_guide_entry.g.dart';

/// Type of regional guide card.
enum GuideCardType {
  @JsonValue('history')   history,    // Historical background
  @JsonValue('geography') geography,  // How the landscape was formed
  @JsonValue('culture')   culture,    // Traditions, food, customs
  @JsonValue('fact')      fact,       // One surprising fact
  @JsonValue('name')      name,       // Origin of the place name
}

extension GuideCardTypeX on GuideCardType {
  String get label {
    switch (this) {
      case GuideCardType.history:   return 'Geschiedenis';
      case GuideCardType.geography: return 'Landschap';
      case GuideCardType.culture:   return 'Cultuur';
      case GuideCardType.fact:      return 'Weetje';
      case GuideCardType.name:      return 'Naam';
    }
  }

  String get emoji {
    switch (this) {
      case GuideCardType.history:   return '🏛️';
      case GuideCardType.geography: return '⛰️';
      case GuideCardType.culture:   return '🎭';
      case GuideCardType.fact:      return '💡';
      case GuideCardType.name:      return '📖';
    }
  }
}

/// A single regional guide card.
/// Generated by AI and cached for 7 days per region.
@freezed
class RegionalGuideEntry with _$RegionalGuideEntry {
  const factory RegionalGuideEntry({
    required String id,
    required String tripId,
    required String regionName,    // e.g. "Sogndal / Lustrafjord"
    required String countryCode,   // "NO"
    required GuideCardType type,
    required String title,         // max 5 words
    required String body,          // 3–6 sentences, narrative
    String? imageQuery,            // for future image search
    required DateTime generatedAt,
  }) = _RegionalGuideEntry;

  factory RegionalGuideEntry.create({
    required String tripId,
    required String regionName,
    required String countryCode,
    required GuideCardType type,
    required String title,
    required String body,
    String? imageQuery,
  }) {
    return RegionalGuideEntry(
      id:          const Uuid().v4(),
      tripId:      tripId,
      regionName:  regionName,
      countryCode: countryCode,
      type:        type,
      title:       title,
      body:        body,
      imageQuery:  imageQuery,
      generatedAt: DateTime.now(),
    );
  }

  factory RegionalGuideEntry.fromJson(Map<String, dynamic> json) =>
      _\$RegionalGuideEntryFromJson(json);
}
